name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456789123
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Display message"
        run: echo "Hola mundo"

      - name: "Showing environment variables"
        if: ${{ env.platform == 'azure' }}
        run:  |
          echo "Esto es el valor de platform: ${{ env.platform }}"
          echo "Esto es el valor de region: ${{ env.region }}"
          echo "Esto es el valor de region: ${{ env.account }}"


